### ISSUE TITLE
user表未必一定和cas服务在同一个库，foreignkey只能建议不能强制

### ISSUE THREAD

**Issue by nickfan** [leo108/laravel_cas_server#3]
```
$table->foreign('user_id')->references(config('cas.user_table.id'))->on(config('cas.user_table.name'))
```
user表未必一定和cas服务在同一个库，foreignkey只能建议不能强制

**Comment by leo108** [comment]
使用外键目的是通过数据库本身的约束来减少代码中针对异常情况的判断处理

**Comment by nickfan** [comment]
但比如类似于我这边的有的老项目和新项目不在同一个框架也不在同一个库，这边cas的外键约束就是个问题

**Comment by leo108** [comment]
使用CAS的目的就是抽离出用户校验的逻辑，个人不建议直接使用现有的用户数据表来作为CAS的用户表，可以把旧项目的用户数据导入到CAS中，然后改造旧项目移除原本的创建（注册）用户逻辑改用CAS即可。
