### ISSUE TITLE
migrate的时候报错

### ISSUE THREAD

**Issue by nickfan** [leo108/laravel_cas_server#4]
<img width="538" alt="qq20170112-0 2x" src="https://cloud.githubusercontent.com/assets/100613/21874755/fbe296d6-d8b1-11e6-8e33-ecbfabecd9b4.png">
<img width="985" alt="qq20170112-1 2x" src="https://cloud.githubusercontent.com/assets/100613/21874756/fbee7500-d8b1-11e6-9400-92ecd2d0cbcb.png">

网上有个解决方案是：
http://stackoverflow.com/questions/23786359/laravel-migration-unique-key-is-too-long-even-if-specified

第二个回答修改database的config配置（注：我的db/table是 mb4的存emoji表情要用）

```
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',
```

**Comment by leo108** [comment]
对于ticket的字段，原则上是不需要支持emoji的，可以考虑在我这边的migration文件里写死字符集，这样就不会受业务方的需求影响。
