### ISSUE TITLE
为啥v2版本不返回attributes?

### ISSUE THREAD

**Issue by nickfan** [leo108/laravel_cas_server#5]
如题，客户端调用的时候v2版本为啥默认不返回attributes?而非要v3版本才返回？

**Comment by leo108** [comment]
CAS的协议就是这样，v3版本才开始返回attributes，https://apereo.github.io/cas/4.2.x/protocol/CAS-Protocol-Specification.html#attributes-cas-30

**Comment by nickfan** [comment]
那为啥我客户端默认从服务器端拿到的用户信息id是User->name，那我所有本地用户以用户name：李狗蛋来做唯一标识？有第二个名字也叫李狗蛋的咋办？不能是User->id么？

**Comment by leo108** [comment]
@nickfan CAS协议里没有user id这种概念，username就是唯一标识符不可重复。

**Comment by nickfan** [comment]
那怎么指定用username字段而不是name字段呢？我表里name是不排重的用户姓名


开 2017年1月16日 在 10:42:34, leo (notifications@github.com) 写到:

@nickfan <https://github.com/nickfan> CAS协议里没有user
id这种概念，username就是唯一标识符不可重复。

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/leo108/laravel_cas_server/issues/5#issuecomment-272761667>,
or mute the thread

**Comment by leo108** [comment]
`interface UserModel` 这个接口，你在实现`getName()`这个方法时可以指定自己的唯一字段

**Comment by nickfan** [comment]
好的，getName这样才是正确的用法，受教了，谢谢。
