### ISSUE TITLE
Protocol v2 CAS Attributes

### ISSUE THREAD

**Issue by orware** [leo108/laravel_cas_server#7]
This may be due to an implementation difference between the CAS Protocol implemented by WSO2 (a product we've been testing for a few months with CAS) but on a test site I have been using, the WSO2 CAS server returns the CAS Attributes section in the XML response, whereas this CAS Server was not.

I eventually tracked it down to this line here:
https://github.com/leo108/laravel_cas_server/blob/master/src/Http/Controllers/ValidateController.php#L105

I'm not sure how much it matters, but it might make sense to have an override that would allow us to configure things so that we can send the CAS Attributes anyway in that case (I haven't tested the official JASIG CAS Server so it may operate exactly as you've built yours here too, but I liked the WSO2 behavior of just including them since it made things a bit more seamless...currently if I were to leave your code unchanged, I'd have to go back to the developer of the CAS client I'm testing out for Joomla to see if he can add CAS v3 support in on his end).

**Comment by leo108** [comment]
@orware the attributes section in response was introduced in V3, you can check the CAS Protocol Specification, [V2](https://apereo.github.io/cas/4.2.x/protocol/CAS-Protocol-Specification.html#252-response) and [V3](https://apereo.github.io/cas/4.2.x/protocol/CAS-Protocol-Specification.html#255-attributes-cas-30)

**Comment by orware** [comment]
Thanks @leo108 I noticed that as well, so it mainly appears that the WSO2 CAS implementation is less strict and displays the cas attributes anyway over the v2 version of the protocol.
