### ISSUE TITLE
lluminate\Contracts\Container\BindingResolutionException

### ISSUE THREAD

**Issue by vaggelis2018** [leo108/laravel_cas_server#9]
Hello man i am getting this error in laravel 5.6 and drupal as a service provider.
Error when validating ticket: Error with request to validate ticket: Server error: `GET https://laravel-idp-cas.test/cas/p3/serviceValidate?service=http%3A//drupal-service-provider.test/casservice&ticket=ST-hrsDSlYhD3ZQOQsAFPRHZgbbVytwx` resulted in a `500 Internal Server Error` response: <!DOCTYPE html><!-- Illuminate\Contracts\Container\BindingResolutionException: Target [NinjaMutex\Lock\LockAbstract] i (truncated...)

**Comment by leo108** [comment]
Are you using https://github.com/leo108/php_cas_server ?

**Comment by vaggelis2018** [comment]
Yes it was my fault it work sorry.

**Comment by vaggelis2018** [comment]
Yes it was my fault it work sorry.
